name: Hprofile Actions
on:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: Maven Test
        run:  mvn Test
      
      - name: checkstyle
        run:  mvn checkstyle:checkstyle